### ISSUE TITLE
Incorrect guidance with $help

### ISSUE THREAD

**Issue by jcortezzo** [AbdulMoMo/GameDeals#4]
The `$help` command will give the following response:

```
Please note the default subreddit is Game Deals. To set a new subreddit please use $select <subreddit_name> or $select <count of posts> <subreddit_name>
```

This guidance isn't correct. There is no such target `$select` that accepts a count of posts. The count only works with the `$show` command. Should be removed from the guidance or added as a feature to assign a new default if no count is specified in `$show`.

**Comment by AbdulMoMo** [comment]
Updated the help command message to use "$show" instead of "$select". Select was a from an older version of the bot before migrating over to using the discord.ext library. Thanks for bringing this up.
